FROM python:3.13-slim

# Need `git` to install `tablemusthave` as long as it's not on PyPi
RUN apt-get clean && apt-get -y update
RUN apt-get -y --no-install-recommends install curl git vim \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install /app/[web]

# Lite deployment runs the app without database integration
ENV METADATA_APP_MODE=lite
# For the given audience, it's easier to just have it in debug mode
ENV FLASK_DEBUG=1
ENV FLASK_APP=/app/metadatalib/app
ENV SQLALCHEMY_ECHO=True
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=80

EXPOSE 80

CMD [ "flask", "run" ]
#CMD [ "gunicorn", "metadatalib.app:app", "--bind", "0.0.0.0:80" ]
