FROM python:3.13-slim

# Need `git` to install `tablemusthave` as long as it's not on PyPi
RUN apt-get clean && apt-get -y update
RUN apt-get -y --no-install-recommends install curl git vim \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN pip install /app/[web]

# Lite deployment runs the app without database integration
ENV FLASK_DEBUG=1
ENV FLASK_APP=/app/metadatalib/app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=80
ENV METADATA_APP_MODE=lite

EXPOSE 80

CMD [ "flask", "run" ]
