[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "metadatalib"
version = "0.0.1"
authors = [
  { name="Charlie Bushman", email="ctbushman@gmail.com" },
]
description = "Utilities for CHOP metadata checker Flask app"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.hatch.build.targets.wheel]
packages = ["src/metadatalib"]
