name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-metadatalib:
    name: Test Metadata Library
    runs-on:
      labels: RIS
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install -U python-dotenv
          python -m pip install -U app/metadatalib/

      - name: Run Tests
        run: |
          cd app/metadatalib
          pytest tests/
