name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-upload-site:
    name: Test Flask Upload Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install -U python-dotenv

      - name: Run Tests
        run: |
          cd metadata_checker_site/Flask
          pytest tests/
  
  test-admin-site:
    name: Test Flask Admin Site
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install -U pytest
          python -m pip install -U python-dotenv

      - name: Run Tests
        run: |
          cd admin_site/Flask
          pytest tests/
  
  test-metadata-admin-tools:
    name: Test Metadata Admin Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          cd metadatacli
          python -m pip install .
          python -m pip install -U pytest
      
      - name: Run Tests
        run: |
          cd metadatacli
          pytest tests/
          
